---
timestamp: '2025-03-03T16:21:18.404209'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs
        exhaust lp033/mystery__pprob27-err-rate-0-3.yaml
    instance_id: mystery__pprob27-err-rate-0-3
    search_algorithm: dfs
    plan_length: 5
    domain_class: mystery
    instance_name: pprob27-err-rate-0-3
    ground_plan:
    - (overcome boils satisfaction scallion mars uranus)
    - (overcome grief satisfaction scallion mercury mars)
    - (feast satisfaction scallion guava arizona pennsylvania)
    - (succumb boils satisfaction guava mercury mars)
    - (succumb grief satisfaction guava mars uranus)
    lifted_plan:
    -   - overcome
        - boils
        - satisfaction
        - scallion
        - ?mars
        - uranus
    -   - overcome
        - grief
        - satisfaction
        - ?scallion
        - mercury
        - mars
    -   - feast
        - satisfaction
        - scallion
        - ?guava
        - arizona
        - pennsylvania
    -   - succumb
        - ?boils
        - satisfaction
        - guava
        - mercury
        - mars
    -   - succumb
        - ?grief
        - satisfaction
        - guava
        - mars
        - uranus


---
timestamp: '2025-03-03T16:21:18.408224'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: feast,(attacks ?l2 ?v),precPos,-1


---
timestamp: '2025-03-03T16:30:22.182815'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: 'Command ''[''/home/projects/u7899572/conda-envs/main/bin/python3'',
        ''instance_solver.py'', ''dfs'', ''/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1'',
        ''/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs exhaust
        lp033/mystery__pprob27-err-rate-0-3.yaml'', ''1000000'', ''mystery__pprob27-err-rate-0-3'',
        ''0.33'', ''unary'']'' died with <Signals.SIGABRT: 6>.'
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 126, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'dfs', '/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1',\
        \ '/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs\
        \ exhaust lp033/mystery__pprob27-err-rate-0-3.yaml', '1000000', 'mystery__pprob27-err-rate-0-3',\
        \ '0.33', 'unary']' died with <Signals.SIGABRT: 6>.\n"
    instance_id: mystery__pprob27-err-rate-0-3
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - dfs
        - /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
        - /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs exhaust
            lp033/mystery__pprob27-err-rate-0-3.yaml
        - '1000000'
        - mystery__pprob27-err-rate-0-3
        - '0.33'
        - unary
        duration: '545.26'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: 'terminate called after throwing an instance of ''Minisat22::OutOfMemoryException''

        '


