---
timestamp: '2025-03-09T20:14:20.122213'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/g_astar-unary-ff
        relax-all lp066/scanalyzer-08-strips__pp28-err-rate-0-5.yaml
    instance_id: scanalyzer-08-strips__pp28-err-rate-0-5
    search_algorithm: g_astar
    plan_length: 15
    domain_class: scanalyzer-08-strips
    instance_name: pp28-err-rate-0-5
    ground_plan:
    - (analyze-4 seg-in-1a seg-in-1b seg-out-1a seg-out-1b car-in-1a car-in-1b car-out-1a
        car-out-1b)
    - (analyze-4 seg-in-3a seg-in-3b seg-out-2a seg-out-2b car-in-3a car-in-3b car-out-2a
        car-out-2b)
    - (analyze-4 seg-in-2a seg-in-2b seg-out-3a seg-out-3b car-in-2a car-in-2b car-out-3a
        car-out-3b)
    - (analyze-4 seg-in-1a seg-in-1b seg-out-1a seg-out-1b car-in-1b car-out-1a car-out-1b
        car-in-1a)
    - (analyze-4 seg-in-1a seg-in-1b seg-out-1a seg-out-1b car-out-1a car-out-1b car-in-1a
        car-in-1b)
    - (analyze-4 seg-in-1a seg-in-1b seg-out-1a seg-out-1b car-out-1b car-in-1a car-in-1b
        car-out-1a)
    - (analyze-4 seg-in-1a seg-in-1b seg-out-1a seg-out-1b car-in-1a car-in-1b car-out-1a
        car-out-1b)
    - (analyze-4 seg-in-2a seg-in-2b seg-out-2a seg-out-2b car-in-2b car-out-3a car-out-2b
        car-in-3a)
    - (analyze-4 seg-in-2a seg-in-2b seg-out-2a seg-out-2b car-out-3a car-out-2b car-in-3a
        car-in-2b)
    - (analyze-4 seg-in-2a seg-in-2b seg-out-2a seg-out-2b car-out-2b car-in-3a car-in-2b
        car-out-3a)
    - (analyze-4 seg-in-2a seg-in-2b seg-out-2a seg-out-2b car-in-3a car-in-2b car-out-3a
        car-out-2b)
    - (analyze-4 seg-in-3a seg-in-3b seg-out-3a seg-out-3b car-in-3b car-out-2a car-out-3b
        car-in-2a)
    - (analyze-4 seg-in-3a seg-in-3b seg-out-3a seg-out-3b car-out-2a car-out-3b car-in-2a
        car-in-3b)
    - (analyze-4 seg-in-3a seg-in-3b seg-out-3a seg-out-3b car-out-3b car-in-2a car-in-3b
        car-out-2a)
    - (analyze-4 seg-in-3a seg-in-3b seg-out-3a seg-out-3b car-in-2a car-in-3b car-out-2a
        car-out-3b)
    lifted_plan:
    -   - analyze-4
        - seg-in-1a
        - seg-in-1b
        - ?seg-out-1a
        - ?seg-out-1b
        - ?car-in-1a
        - ?car-in-1b
        - car-out-1a
        - ?car-out-1b
    -   - analyze-4
        - ?seg-in-3a
        - ?seg-in-3b
        - seg-out-2a
        - ?seg-out-2b
        - ?car-in-3a
        - car-in-3b
        - ?car-out-2a
        - ?car-out-2b
    -   - analyze-4
        - seg-in-2a
        - seg-in-2b
        - seg-out-3a
        - seg-out-3b
        - ?car-in-2a
        - car-in-2b
        - car-out-3a
        - car-out-3b
    -   - analyze-4
        - ?seg-in-1a
        - ?seg-in-1b
        - ?seg-out-1a
        - ?seg-out-1b
        - car-in-1b
        - car-out-1a
        - ?car-out-1b
        - car-in-1a
    -   - analyze-4
        - ?seg-in-1a
        - seg-in-1b
        - ?seg-out-1a
        - ?seg-out-1b
        - car-out-1a
        - ?car-out-1b
        - car-in-1a
        - car-in-1b
    -   - analyze-4
        - ?seg-in-1a
        - ?seg-in-1b
        - seg-out-1a
        - ?seg-out-1b
        - ?car-out-1b
        - car-in-1a
        - ?car-in-1b
        - ?car-out-1a
    -   - analyze-4
        - ?seg-in-1a
        - seg-in-1b
        - seg-out-1a
        - ?seg-out-1b
        - ?car-in-1a
        - ?car-in-1b
        - ?car-out-1a
        - car-out-1b
    -   - analyze-4
        - ?seg-in-2a
        - ?seg-in-2b
        - seg-out-2a
        - ?seg-out-2b
        - car-in-2b
        - ?car-out-3a
        - car-out-2b
        - ?car-in-3a
    -   - analyze-4
        - ?seg-in-2a
        - ?seg-in-2b
        - ?seg-out-2a
        - ?seg-out-2b
        - ?car-out-3a
        - ?car-out-2b
        - ?car-in-3a
        - ?car-in-2b
    -   - analyze-4
        - ?seg-in-2a
        - ?seg-in-2b
        - ?seg-out-2a
        - ?seg-out-2b
        - car-out-2b
        - car-in-3a
        - car-in-2b
        - car-out-3a
    -   - analyze-4
        - seg-in-2a
        - seg-in-2b
        - ?seg-out-2a
        - ?seg-out-2b
        - car-in-3a
        - ?car-in-2b
        - car-out-3a
        - car-out-2b
    -   - analyze-4
        - seg-in-3a
        - ?seg-in-3b
        - seg-out-3a
        - ?seg-out-3b
        - ?car-in-3b
        - car-out-2a
        - car-out-3b
        - car-in-2a
    -   - analyze-4
        - seg-in-3a
        - ?seg-in-3b
        - ?seg-out-3a
        - ?seg-out-3b
        - ?car-out-2a
        - car-out-3b
        - ?car-in-2a
        - car-in-3b
    -   - analyze-4
        - ?seg-in-3a
        - ?seg-in-3b
        - seg-out-3a
        - ?seg-out-3b
        - car-out-3b
        - ?car-in-2a
        - ?car-in-3b
        - car-out-2a
    -   - analyze-4
        - ?seg-in-3a
        - ?seg-in-3b
        - seg-out-3a
        - ?seg-out-3b
        - car-in-2a
        - ?car-in-3b
        - ?car-out-2a
        - ?car-out-3b


---
timestamp: '2025-03-09T20:14:20.128434'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: analyze-4,(cycle-4 ?s2 ?s2 ?s3 ?s2),precPos,-1


---
timestamp: '2025-03-09T20:14:29.249048'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',
        'instance_solver.py', 'g_astar-unary-ff-sg3-lp066.yaml', 'scanalyzer-08-strips__pp28-err-rate-0-5']'
        returned non-zero exit status 1.
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 119, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'g_astar-unary-ff-sg3-lp066.yaml', 'scanalyzer-08-strips__pp28-err-rate-0-5']'\
        \ returned non-zero exit status 1.\n"
    instance_id: scanalyzer-08-strips__pp28-err-rate-0-5
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - g_astar-unary-ff-sg3-lp066.yaml
        - scanalyzer-08-strips__pp28-err-rate-0-5
        duration: '10.60'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: '

        '
    stderr: "Traceback (most recent call last):\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/lifted_pddl_grounder.py\"\
        , line 131, in ground_pddl\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/lifted_pddl/parser.py\"\
        , line 485, in get_applicable_actions\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/lifted_pddl/parser.py\"\
        , line 433, in _get_applicable_var_assigns_action\nMemoryError\n\nDuring handling\
        \ of the above exception, another exception occurred:\n\nTraceback (most recent\
        \ call last):\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
        , line 195, in get_neighbors\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/lifted_pddl_grounder.py\"\
        , line 140, in ground_pddl\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/tempfile.py\"\
        , line 836, in __exit__\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/tempfile.py\"\
        , line 840, in cleanup\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/tempfile.py\"\
        , line 822, in _rmtree\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/shutil.py\"\
        , line 718, in rmtree\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/shutil.py\"\
        , line 627, in _rmtree_safe_fd\nMemoryError\n\nDuring handling of the above\
        \ exception, another exception occurred:\n\nTraceback (most recent call last):\n\
        \  File \"instance_solver.py\", line 125, in solve_instance\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
        , line 78, in find_path\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
        , line 203, in get_neighbors\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/custom_logger.py\"\
        , line 44, in log\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/__init__.py\"\
        , line 253, in dump\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/__init__.py\"\
        , line 241, in dump_all\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 27, in represent\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 48, in represent_data\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 207, in represent_dict\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 118, in represent_mapping\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 48, in represent_data\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 207, in represent_dict\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 118, in represent_mapping\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 48, in represent_data\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/yaml/representer.py\"\
        , line 207, in represent_dict\nMemoryError\n\nDuring handling of the above\
        \ exception, another exception occurred:\n\nTraceback (most recent call last):\n\
        \  File \"instance_solver.py\", line 147, in <module>\n  File \"instance_solver.py\"\
        , line 129, in solve_instance\nMemoryError\n"


