---
timestamp: '2025-03-15T20:53:52.383103'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/gbfs-unary-ff
        exhaust lp033/mprime__pprob07-err-rate-0-1.yaml
    instance_id: mprime__pprob07-err-rate-0-1
    search_algorithm: gbfs
    plan_length: 5
    domain_class: mprime
    instance_name: pprob07-err-rate-0-1
    ground_plan:
    - (drink shrimp snickers moravia manitoba arizona arizona manitoba)
    - (feast stimulation snickers popover arizona manitoba)
    - (overcome jealousy stimulation popover mercury saturn)
    - (feast stimulation popover muffin arizona manitoba)
    - (succumb jealousy stimulation muffin mercury saturn)
    lifted_plan:
    -   - drink
        - shrimp
        - snickers
        - moravia
        - ?manitoba
        - arizona
        - arizona
        - manitoba
    -   - feast
        - ?stimulation
        - snickers
        - popover
        - arizona
        - manitoba
    -   - overcome
        - ?jealousy
        - stimulation
        - popover
        - ?mercury
        - saturn
    -   - feast
        - stimulation
        - popover
        - muffin
        - ?arizona
        - manitoba
    -   - succumb
        - jealousy
        - stimulation
        - muffin
        - ?mercury
        - saturn


---
timestamp: '2025-03-15T20:53:52.387181'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-03-15T20:53:52.421776'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: CalledProcessError
    error_message: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',
        'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp033.yaml',
        'mprime__pprob07-err-rate-0-1']' returned non-zero exit status 1.
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 119, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp033.yaml',\
        \ 'mprime__pprob07-err-rate-0-1']' returned non-zero exit status 1.\n"
    instance_id: mprime__pprob07-err-rate-0-1
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - configs_exhaustive/gbfs-unary-ff_exhaust_lp033.yaml
        - mprime__pprob07-err-rate-0-1
        duration: '1.90'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: "Traceback (most recent call last):\n  File \"instance_solver.py\", line\
        \ 147, in <module>\n    solve_instance(\n  File \"instance_solver.py\", line\
        \ 122, in solve_instance\n    raise NotImplementedError(\"Search algorithm\
        \ not supported.\")\nNotImplementedError: Search algorithm not supported.\n"


