---
timestamp: '2025-03-17T10:33:51.220843'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/gbfs-unary
        exhaust lp033/zenotravel__pp04-err-rate-0-1.yaml
    instance_id: zenotravel__pp04-err-rate-0-1
    search_algorithm: gbfs
    plan_length: 9
    domain_class: zenotravel
    instance_name: pp04-err-rate-0-1
    ground_plan:
    - (fly plane1 city2 city0 fl5 fl4)
    - (board person4 plane1 city0)
    - (fly plane1 city0 city1 fl4 fl3)
    - (debark person4 plane1 city1)
    - (board person2 plane1 city1)
    - (fly plane1 city1 city0 fl3 fl2)
    - (fly plane1 city0 city2 fl2 fl1)
    - (debark person2 plane1 city2)
    - (fly plane1 city2 city0 fl1 fl0)
    lifted_plan:
    -   - fly
        - plane1
        - city2
        - city0
        - ?fl5
        - fl4
    -   - board
        - person4
        - plane1
        - ?city0
    -   - fly
        - plane1
        - city0
        - city1
        - fl4
        - ?fl3
    -   - debark
        - person4
        - plane1
        - ?city1
    -   - board
        - person2
        - plane1
        - city1
    -   - fly
        - plane1
        - ?city1
        - city0
        - fl3
        - fl2
    -   - fly
        - plane1
        - ?city0
        - city2
        - fl2
        - fl1
    -   - debark
        - person2
        - plane1
        - city2
    -   - fly
        - ?plane1
        - city2
        - city0
        - ?fl1
        - fl0


---
timestamp: '2025-03-17T10:33:51.224100'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-03-17T10:33:51.251012'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: CalledProcessError
    error_message: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',
        'instance_solver.py', 'configs_exhaustive/gbfs-unary_exhaust_lp033.yaml',
        'zenotravel__pp04-err-rate-0-1']' returned non-zero exit status 1.
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 119, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'configs_exhaustive/gbfs-unary_exhaust_lp033.yaml',\
        \ 'zenotravel__pp04-err-rate-0-1']' returned non-zero exit status 1.\n"
    instance_id: zenotravel__pp04-err-rate-0-1
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - configs_exhaustive/gbfs-unary_exhaust_lp033.yaml
        - zenotravel__pp04-err-rate-0-1
        duration: '1.56'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: "Traceback (most recent call last):\n  File \"instance_solver.py\", line\
        \ 147, in <module>\n    solve_instance(\n  File \"instance_solver.py\", line\
        \ 122, in solve_instance\n    raise NotImplementedError(\"Search algorithm\
        \ not supported.\")\nNotImplementedError: Search algorithm not supported.\n"


