---
timestamp: '2025-01-16T23:36:01.246973'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/astar-zeroary
        relax-prec-delete lp1/zenotravel__pp03-err-rate-0-1.yaml
    instance_id: zenotravel__pp03-err-rate-0-1
    search_algorithm: astar
    plan_length: 6
    domain_class: zenotravel
    instance_name: pp03-err-rate-0-1
    ground_plan:
    - (board person1 plane1 city0)
    - (fly plane1 city0 city1 fl4 fl3)
    - (board person3 plane1 city1)
    - (debark person1 plane1 city1)
    - (fly plane1 city1 city0 fl3 fl2)
    - (debark person3 plane1 city0)
    lifted_plan:
    -   - board
        - ?person1
        - ?plane1
        - ?city0
    -   - fly
        - ?plane1
        - ?city0
        - ?city1
        - ?fl4
        - ?fl3
    -   - board
        - ?person3
        - ?plane1
        - ?city1
    -   - debark
        - ?person1
        - ?plane1
        - ?city1
    -   - fly
        - ?plane1
        - ?city1
        - ?city0
        - ?fl3
        - ?fl2
    -   - debark
        - ?person3
        - ?plane1
        - ?city0


---
timestamp: '2025-01-16T23:36:01.663034'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-01-16T23:48:22.310801'
level: ERROR
issuer: instance_solver
event_type: error
data: "An error occurred during A* search: 'Node' object has no attribute 'neighbours'.\
    \ Stack trace: Traceback (most recent call last):\n  File \"instance_solver.py\"\
    , line 104, in solve_instance\n    searcher.find_path(logger=logger, log_interval=log_interval)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 75, in find_path\n    self.log_iteration_info(logger, iteration, open_list,\
    \ current_node, final=True, is_goal=True)\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 37, in log_iteration_info\n    \"current_node\": current_node.to_dict(include_state=False)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
    , line 233, in to_dict\n    \"num_neighbours\": len(self.neighbours),\nAttributeError:\
    \ 'Node' object has no attribute 'neighbours'\n"


---
timestamp: '2025-01-16T23:48:24.813230'
level: INFO
issuer: instance_solver
event_type: timer_seconds
data: '850.82'


---
timestamp: '2025-01-16T23:48:35.197353'
level: ERROR
issuer: batch_solver
event_type: error
data: Subprocess timed out after 900 seconds.


