> Solving the next problem at: 2024-09-27 08:34:28 UTC
> Search algorithm: bfs
> Instance ID=pegsol-08-strips/pp05-err-rate-0-5
> Plan length=14
> Domain class: pegsol-08-strips
> Instance name: pp05-err-rate-0-5
> Ground plan:
['(jump-new-move pos-2-5 pos-2-4 pos-2-3)', '(end-move pos-2-3)', '(jump-new-move pos-4-1 pos-4-2 pos-4-3)', '(end-move pos-4-3)', '(jump-new-move pos-2-3 pos-2-2 pos-2-1)', '(end-move pos-2-1)', '(jump-new-move pos-2-1 pos-3-1 pos-4-1)', '(end-move pos-4-1)', '(jump-new-move pos-4-4 pos-4-3 pos-4-2)', '(end-move pos-4-2)', '(jump-new-move pos-4-1 pos-4-2 pos-4-3)', '(jump-continue-move pos-4-3 pos-3-3 pos-2-3)', '(end-move pos-2-3)', '(jump-new-move pos-1-3 pos-2-3 pos-3-3)']
> Lifted plan:
['jump-new-move', 'end-move', 'jump-new-move', 'end-move', 'jump-new-move', 'end-move', 'jump-new-move', 'end-move', 'jump-new-move', 'end-move', 'jump-new-move', 'jump-continue-move', 'end-move', 'jump-new-move']
>>>  Vanilla ground repair length:
2

>>>  Vanilla ground repair:
jump-new-move,(in-line ?over ?over ?to),precPos,-1
jump-new-move,(in-line ?from ?from ?from),effPos,1

An error occurred during A* search: name 'logger' is not defined
Traceback (most recent call last):
  File "/home/nader/projects/lifted-white-plan-domain-repair/instance_solver.py", line 70, in solve_instance
    path, goal_node = searcher.find_path(log_interval=log_interval)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py", line 49, in find_path
    for neighbor in current_node.get_neighbors():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/node.py", line 167, in get_neighbors
    logger.debug(f'> Current state:\n{self.current_state}')
    ^^^^^^
NameError: name 'logger' is not defined. Did you mean: 'self.logger'?

> Time spent on this problem: 0.0 hours = 0.0 minutes = 0.21 seconds
> Subprocess finished.
