---
timestamp: '2025-01-17T02:36:04.581507'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/astar-zeroary
        relax-prec-delete lp033/visitall-opt11-strips__pproblem03-half-err-rate-0-3.yaml
    instance_id: visitall-opt11-strips__pproblem03-half-err-rate-0-3
    search_algorithm: astar
    plan_length: 7
    domain_class: visitall-opt11-strips
    instance_name: pproblem03-half-err-rate-0-3
    ground_plan:
    - (move loc-x1-y1 loc-x0-y1)
    - (move loc-x0-y1 loc-x0-y2)
    - (move loc-x0-y2 loc-x0-y1)
    - (move loc-x0-y1 loc-x0-y0)
    - (move loc-x0-y0 loc-x1-y0)
    - (move loc-x1-y0 loc-x2-y0)
    - (move loc-x2-y0 loc-x2-y1)
    lifted_plan:
    -   - move
        - loc-x1-y1
        - loc-x0-y1
    -   - move
        - loc-x0-y1
        - ?loc-x0-y2
    -   - move
        - loc-x0-y2
        - loc-x0-y1
    -   - move
        - loc-x0-y1
        - ?loc-x0-y0
    -   - move
        - loc-x0-y0
        - loc-x1-y0
    -   - move
        - loc-x1-y0
        - loc-x2-y0
    -   - move
        - ?loc-x2-y0
        - loc-x2-y1


---
timestamp: '2025-01-17T02:36:05.037177'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: move,(visited ?nextpos),precPos,-1


---
timestamp: '2025-01-17T02:36:07.950820'
level: ERROR
issuer: instance_solver
event_type: error
data: "An error occurred during A* search: 'Node' object has no attribute 'neighbours'.\
    \ Stack trace: Traceback (most recent call last):\n  File \"instance_solver.py\"\
    , line 104, in solve_instance\n    searcher.find_path(logger=logger, log_interval=log_interval)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 95, in find_path\n    self.log_iteration_info(logger, iteration, open_list,\
    \ current_node, final=True, is_goal=False)\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 37, in log_iteration_info\n    \"current_node\": current_node.to_dict(include_state=False)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
    , line 233, in to_dict\n    \"num_neighbours\": len(self.neighbours),\nAttributeError:\
    \ 'Node' object has no attribute 'neighbours'\n"


---
timestamp: '2025-01-17T02:36:08.133981'
level: INFO
issuer: instance_solver
event_type: timer_seconds
data: '107.96'


---
timestamp: '2025-01-17T02:37:46.848435'
level: INFO
issuer: batch_solver
event_type: general
data: 'Subprocess finished successfully. Duration: 241.20 seconds'


