---
timestamp: '2025-03-02T17:27:48.656461'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug/bfs
        exhast lp066/zenotravel__pp03-err-rate-0-3.yaml
    instance_id: zenotravel__pp03-err-rate-0-3
    search_algorithm: bfs
    plan_length: 6
    domain_class: zenotravel
    instance_name: pp03-err-rate-0-3
    ground_plan:
    - (board person1 plane1 city0)
    - (fly plane1 city0 city1 fl4 fl3)
    - (board person3 plane1 city1)
    - (debark person1 plane1 city1)
    - (fly plane1 city1 city0 fl3 fl2)
    - (debark person3 plane1 city0)
    lifted_plan:
    -   - board
        - person1
        - plane1
        - ?city0
    -   - fly
        - ?plane1
        - ?city0
        - ?city1
        - fl4
        - ?fl3
    -   - board
        - ?person3
        - ?plane1
        - city1
    -   - debark
        - ?person1
        - ?plane1
        - city1
    -   - fly
        - ?plane1
        - ?city1
        - city0
        - fl3
        - fl2
    -   - debark
        - person3
        - ?plane1
        - city0


---
timestamp: '2025-03-02T17:27:48.659922'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: board,(in ?p ?a),effPos,1


---
timestamp: '2025-03-02T17:39:40.856968'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: 'Command ''[''/home/projects/u7899572/conda-envs/main/bin/python3'',
        ''instance_solver.py'', ''bfs'', ''/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1'',
        ''/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug/bfs
        exhast lp066/zenotravel__pp03-err-rate-0-3.yaml'', ''1000000'', ''zenotravel__pp03-err-rate-0-3'',
        ''0.66'', ''unary'']'' died with <Signals.SIGABRT: 6>.'
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 126, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'bfs', '/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1',\
        \ '/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug/bfs\
        \ exhast lp066/zenotravel__pp03-err-rate-0-3.yaml', '1000000', 'zenotravel__pp03-err-rate-0-3',\
        \ '0.66', 'unary']' died with <Signals.SIGABRT: 6>.\n"
    instance_id: zenotravel__pp03-err-rate-0-3
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - bfs
        - /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
        - /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug/bfs
            exhast lp066/zenotravel__pp03-err-rate-0-3.yaml
        - '1000000'
        - zenotravel__pp03-err-rate-0-3
        - '0.66'
        - unary
        duration: '716.40'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: 'terminate called after throwing an instance of ''Minisat22::OutOfMemoryException''

        '


